// HakSpring Romanizer (Romaine) - 「蘿蔓生菜」客語羅馬字轉換器
// Written by Roo, the AI Software Engineer
// Based on spec 1.4 generated by Gemini 2.5 Pro based on ideas of Aiuanyu

document.addEventListener('DOMContentLoaded', () => {
  let romanizerSelectedDialect = '四縣'; // <-- 新增此行，預設為「四縣」

  // DOM Elements
  const showRomanizerBtn = document.getElementById('showRomanizerBtn');
  const romanizerContainer = document.getElementById('romanizerContainer');
  const romanizerCloseBtn = document.getElementById('romanizerCloseBtn');
  const romanizerStartBtn = document.getElementById('romanizer-start-btn');
  const segmentationWorkspace = document.getElementById('segmentation-workspace');
  const copyRomanizerResultBtn = document.getElementById('copy-romanizer-result-btn');
  const romanizerDialectSelector = document.getElementById('romanizer-dialect-selector');
  const romanizerInput = document.getElementById('romanizer-input');
  const romanizerOutput = document.getElementById('romanizer-output');

  // --- Event Listeners (修正後) ---
  if (romanizerDialectSelector) {
    romanizerDialectSelector.addEventListener('change', function() {
      romanizerSelectedDialect = this.value;
      console.log(`Romanizer 腔調已切換為: ${romanizerSelectedDialect}`);
    });
  }
  if (showRomanizerBtn) {
    showRomanizerBtn.addEventListener('click', showRomanizer);
  }
  if (romanizerCloseBtn) {
    romanizerCloseBtn.addEventListener('click', hideRomanizer);
  }
  if (romanizerStartBtn) {
    romanizerStartBtn.addEventListener('click', startSegmentation);
  }
  if (segmentationWorkspace) {
    segmentationWorkspace.addEventListener('click', handleSegmentClick);
  }
  if (copyRomanizerResultBtn) {
    copyRomanizerResultBtn.addEventListener('click', copyRomanizerResult);
  }

  // --- Functions (修正後) ---
  function showRomanizer() {
    if (romanizerContainer) {
      romanizerContainer.style.display = 'block';
      romanizerContainer.scrollIntoView({ behavior: 'smooth', block: 'start' });

      // --- 優化腔調擇單預設邏輯 ---
      if (typeof currentActiveMainDialectName !== 'undefined' && romanizerDialectSelector) {
        const mainDialect = currentActiveMainDialectName;
        // 檢查 main.js 傳來个腔調，係無係一個有效个選項
        const isValidOption = Array.from(romanizerDialectSelector.options).some(opt => opt.value === mainDialect);

        // 若係有效選項就用佢，若無 (例如係空字串)，就 fallback 到 '四縣'
        const dialectToSet = (mainDialect && isValidOption) ? mainDialect : '四縣';

        romanizerDialectSelector.value = dialectToSet;

        // 同步更新 Romanizer 內部个狀態變數
        romanizerSelectedDialect = romanizerDialectSelector.value;
        console.log(`Romanizer opened. Dialect set to: ${romanizerSelectedDialect}`);
      }
    }
  }

  function hideRomanizer() {
    if (romanizerContainer) {
      romanizerContainer.style.display = 'none';
    }
  }
  function startSegmentation() {
    if (!romanizerInput || !segmentationWorkspace || !romanizerOutput) return;
    segmentationWorkspace.innerHTML = '';
    romanizerOutput.innerHTML = '';
    const text = romanizerInput.value;
    if (!text) return;
  
    const segmentRegex = /([^\u4e00-\u9fa5\u3400-\u4dbf\u{20000}-\u{2a6df}\u{2a700}-\u{2b73f}\u{2b740}-\u{2b81f}\u{2b820}-\u{2ceaf}\u{2ceb0}-\u{2ebef}]+)/u;
    const segments = text.split(segmentRegex).filter(Boolean);
  
    segments.forEach(segment => {
      const span = document.createElement('span');
      span.textContent = segment;
      if (!segmentRegex.test(segment)) {
        span.classList.add('segment-word');
        const readings = findPronunciationsInAllData(segment);
        const exactMatches = readings.filter(r => r.isExactMatch);
        if (exactMatches.length > 0) {
          let preferredReading = exactMatches.find(r => r.source.startsWith(romanizerSelectedDialect)) || exactMatches[0];
          span.dataset.romanized = preferredReading.pronunciation;
          span.classList.add('completed');
          if (exactMatches.length > 1) {
            span.classList.add('auto-filled-multiple');
          }
        } else {
          span.dataset.romanized = '--iMazinGrace-1';
          span.classList.add('no-result');
        }
      }
      segmentationWorkspace.appendChild(span);
    });
    updateAllRomanizerOutput();
  }
  function handleSegmentClick(event) {
    const target = event.target;
    // Make sure the clicked element is a word segment
    if (target.classList.contains('segment-word')) {
      const searchText = target.textContent;
      
      // Check if dependent functions from main.js exist
      if (typeof findPronunciationsInAllData !== 'function' || typeof showPronunciationPopup !== 'function') {
        console.error('Core functions (findPronunciationsInAllData or showPronunciationPopup) are not defined. Make sure main.js is loaded before romanizer.js.');
        alert('核心查詢功能載入失敗，請重新整理頁面。');
        return;
      }
      
      const readings = findPronunciationsInAllData(searchText);
      
      // Call the popup function, passing the clicked span as the anchor,
      // and a new callback function to handle the selection.
      // Call the new, self-contained popup function
      showPronunciationPopup(searchText, readings, target, (anchor, phonetic) => {
        updateRomanizerOutput(anchor, phonetic);
      }, romanizerSelectedDialect); // <-- 在此傳入 Romanizer 選擇的腔調
    }
  }
  function copyRomanizerResult() {
    if (!romanizerOutput || !copyRomanizerResultBtn) return;
    const textToCopy = romanizerOutput.textContent;
    if (textToCopy) {
      navigator.clipboard.writeText(textToCopy).then(() => {
        // Optional: Provide user feedback
        const originalButtonContent = copyRomanizerResultBtn.innerHTML;
        copyRomanizerResultBtn.innerHTML = '<i class="fas fa-check"></i> 已複製';
        copyRomanizerResultBtn.disabled = true;
        setTimeout(() => {
          copyRomanizerResultBtn.innerHTML = originalButtonContent;
          copyRomanizerResultBtn.disabled = false;
        }, 2000);
      }).catch(err => {
        console.error('無法複製文字: ', err);
        alert('複製失敗，請手動複製。');
      });
    }
  }
  function updateRomanizerOutput(targetSpan, selectedRomanization) {
    if (!targetSpan) return;
    targetSpan.dataset.romanized = selectedRomanization;
    targetSpan.classList.add('completed');
    targetSpan.classList.remove('auto-filled-multiple');
    targetSpan.classList.remove('no-result');
    updateAllRomanizerOutput();
  }

  function updateAllRomanizerOutput() {
    if (!romanizerOutput || !segmentationWorkspace) return;
    const allSpans = segmentationWorkspace.querySelectorAll('span');
    let resultString = '';
    allSpans.forEach(span => {
      const text = span.dataset.romanized || span.textContent;
      resultString += text + ' ';
    });
    romanizerOutput.textContent = resultString.trim();
  }
});