// HakSpring Romanizer (Romaine) - 「蘿蔓生菜」客語羅馬字轉換器
// Written by Roo, the AI Software Engineer
// Based on spec 1.4 generated by Gemini 2.5 Pro based on ideas of Aiuanyu

document.addEventListener('DOMContentLoaded', () => {
  let romanizerSelectedDialect = '四縣'; // <-- 新增此行，預設為「四縣」
  const ROMANIZER_JOINING_MODE_KEY = 'romanizerJoiningMode';
  let romanizerJoiningMode = 'none'; // 【新增】預設連詞模式

  // DOM Elements
  const showRomanizerBtn = document.getElementById('showRomanizerBtn');
  const romanizerContainer = document.getElementById('romanizerContainer');
  const romanizerCloseBtn = document.getElementById('romanizerCloseBtn');
  const romanizerStartBtn = document.getElementById('romanizer-start-btn');
  const segmentationWorkspace = document.getElementById('segmentation-workspace');
  const copyRomanizerResultBtn = document.getElementById('copy-romanizer-result-btn');
  const romanizerDialectSelector = document.getElementById('romanizer-dialect-selector');
  const romanizerJoiningModeSelector = document.getElementById('romanizer-joining-mode-selector'); // 【新增】
  const romanizerInput = document.getElementById('romanizer-input');
  const romanizerOutput = document.getElementById('romanizer-output');

  // 【新增】頁面載入時，讀取使用者偏好
  const savedJoiningMode = localStorage.getItem(ROMANIZER_JOINING_MODE_KEY);
  if (savedJoiningMode && romanizerJoiningModeSelector) {
    romanizerJoiningMode = savedJoiningMode;
    romanizerJoiningModeSelector.value = savedJoiningMode;
    console.log(`從 localStorage 載入連詞模式: ${savedJoiningMode}`);
  }

  // --- Event Listeners (修正後) ---
  if (romanizerDialectSelector) {
    romanizerDialectSelector.addEventListener('change', function() {
      romanizerSelectedDialect = this.value;
      console.log(`Romanizer 腔調已切換為: ${romanizerSelectedDialect}`);

      // --- ↓↓↓ 新增以下程式碼 ↓↓↓ ---
      if (segmentationWorkspace) {
        segmentationWorkspace.innerHTML = '';
      }
      if (romanizerOutput) {
        romanizerOutput.innerHTML = '';
      }
      // --- ↑↑↑ 新增結束 ↑↑↑ ---
    });
  }

  // 【新增】監聽連詞模式選擇器个變化
  if (romanizerJoiningModeSelector) {
    romanizerJoiningModeSelector.addEventListener('change', function() {
      romanizerJoiningMode = this.value;
      localStorage.setItem(ROMANIZER_JOINING_MODE_KEY, romanizerJoiningMode);
      console.log(`連詞模式已切換並儲存: ${romanizerJoiningMode}`);

      // 若工作區有內容，就即時更新結果
      if (segmentationWorkspace && segmentationWorkspace.innerHTML.trim() !== '') {
        updateAllRomanizerOutput();
      }
    });
  }
  if (showRomanizerBtn) {
    showRomanizerBtn.addEventListener('click', showRomanizer);
  }
  if (romanizerCloseBtn) {
    romanizerCloseBtn.addEventListener('click', hideRomanizer);
  }
  if (romanizerStartBtn) {
    romanizerStartBtn.addEventListener('click', startSegmentation);
  }
  if (segmentationWorkspace) {
    segmentationWorkspace.addEventListener('click', handleSegmentClick);
  }
  if (copyRomanizerResultBtn) {
    copyRomanizerResultBtn.addEventListener('click', copyRomanizerResult);
  }

  // --- Functions (修正後) ---
  function showRomanizer() {
    if (romanizerContainer) {
      romanizerContainer.style.display = 'block';
      romanizerContainer.scrollIntoView({ behavior: 'smooth', block: 'start' });

      // --- 優化腔調擇單預設邏輯 ---
      if (typeof currentActiveMainDialectName !== 'undefined' && romanizerDialectSelector) {
        const mainDialect = currentActiveMainDialectName;
        // 檢查 main.js 傳來个腔調，係無係一個有效个選項
        const isValidOption = Array.from(romanizerDialectSelector.options).some(opt => opt.value === mainDialect);

        // 若係有效選項就用佢，若無 (例如係空字串)，就 fallback 到 '四縣'
        const dialectToSet = (mainDialect && isValidOption) ? mainDialect : '四縣';

        romanizerDialectSelector.value = dialectToSet;

        // 同步更新 Romanizer 內部个狀態變數
        romanizerSelectedDialect = romanizerDialectSelector.value;
        console.log(`Romanizer opened. Dialect set to: ${romanizerSelectedDialect}`);
      }
    }
  }

  function hideRomanizer() {
    if (romanizerContainer) {
      romanizerContainer.style.display = 'none';
    }
  }
  // --- 取代舊的 startSegmentation 函式 ---
function startSegmentation() {
  if (!romanizerInput || !segmentationWorkspace || !romanizerOutput) return;

  segmentationWorkspace.innerHTML = '';
  romanizerOutput.innerHTML = '';

  const text = romanizerInput.value;
  if (!text) return;

  const segmentRegex = /([^\u4e00-\u9fa5\u3400-\u4dbf\u{20000}-\u{2a6df}\u{2a700}-\u{2b73f}\u{2b740}-\u{2b81f}\u{2b820}-\u{2ceaf}\u{2ceb0}-\u{2ebef}]+)/u;
  const segments = text.split(segmentRegex).filter(Boolean);

  segments.forEach(segment => {
    const span = document.createElement('span');
    span.textContent = segment;

    if (!segmentRegex.test(segment)) {
      span.classList.add('segment-word');

      const readings = findPronunciationsInAllData(segment);
      const exactMatches = readings.filter(r => r.isExactMatch);

      if (exactMatches.length > 0) {
        const dialectSpecificMatches = exactMatches.filter(r => isSourceMatchingDialect(r.source, romanizerSelectedDialect));

        if (dialectSpecificMatches.length > 0) {
          const preferredReading = dialectSpecificMatches[0];
          span.dataset.romanized = preferredReading.pronunciation;
          span.classList.add('completed');

          // --- ↓↓↓ 修正後个核心邏輯 ↓↓↓ ---
          // 檢查「符合當前腔調」的結果中，有多少種「不同」的讀音
          const uniquePronunciationsInDialect = [...new Set(dialectSpecificMatches.map(r => r.pronunciation))];

          // 只有在當前腔調下存在多種不同讀音時，才標示為黃色待確認
          if (uniquePronunciationsInDialect.length > 1) {
            span.classList.add('auto-filled-multiple');
          }
          // --- ↑↑↑ 修正結束 ↑↑↑ ---

        } else {
          span.dataset.romanized = ''; // 或者 span.dataset.romanized = null; 亦可
          span.classList.add('no-result');
        }
      } else {
        span.dataset.romanized = '--iMazinGrace-1';
        span.classList.add('no-result');
      }
    }
    segmentationWorkspace.appendChild(span);
  });

  updateAllRomanizerOutput();
}
  function handleSegmentClick(event) {
    const target = event.target;
    // Make sure the clicked element is a word segment
    if (target.classList.contains('segment-word')) {
      const searchText = target.textContent;
      
      // Check if dependent functions from main.js exist
      if (typeof findPronunciationsInAllData !== 'function' || typeof showPronunciationPopup !== 'function') {
        console.error('Core functions (findPronunciationsInAllData or showPronunciationPopup) are not defined. Make sure main.js is loaded before romanizer.js.');
        alert('核心查詢功能載入失敗，請重新整理頁面。');
        return;
      }
      
      const readings = findPronunciationsInAllData(searchText);
      
      // Call the popup function, passing the clicked span as the anchor,
      // and a new callback function to handle the selection.
      // Call the new, self-contained popup function
      showPronunciationPopup(searchText, readings, target, (anchor, phonetic) => {
        updateRomanizerOutput(anchor, phonetic);
      }, romanizerSelectedDialect); // <-- 在此傳入 Romanizer 選擇的腔調
    }
  }
  function copyRomanizerResult() {
    if (!romanizerOutput || !copyRomanizerResultBtn) return;

    // 【新】用正規表示式將多隻空白換做一隻，再過 trim()
    const textToCopy = romanizerOutput.textContent.replace(/\s+/g, ' ').trim();

    if (textToCopy) {
      navigator.clipboard.writeText(textToCopy).then(() => {
        // Optional: Provide user feedback
        const originalButtonContent = copyRomanizerResultBtn.innerHTML;
        copyRomanizerResultBtn.innerHTML = '<i class="fas fa-check"></i> 已複製';
        copyRomanizerResultBtn.disabled = true;
        setTimeout(() => {
          copyRomanizerResultBtn.innerHTML = originalButtonContent;
          copyRomanizerResultBtn.disabled = false;
        }, 2000);
      }).catch(err => {
        console.error('無法複製文字: ', err);
        alert('複製失敗，請手動複製。');
      });
    }
  }
  function updateRomanizerOutput(targetSpan, selectedRomanization) {
    if (!targetSpan) return;
    targetSpan.dataset.romanized = selectedRomanization;
    targetSpan.classList.add('completed');
    targetSpan.classList.remove('auto-filled-multiple');
    targetSpan.classList.remove('no-result');
    updateAllRomanizerOutput();
  }

  // --- 新增：標點正規化函式 ---
  function normalizePunctuation(punc) {
    const punctuationMap = {
      '，': ',', '。': '.', '？': '?', '！': '!', '；': ';', '：': ':',
      '（': '(', '）': ')', '、': ',', // 頓號也轉做逗號
      '「': '“', '」': '”', '『': '‘', '』': '’'
    };
    // 逐一替換，處理連續標點个情況
    let result = '';
    for (let i = 0; i < punc.length; i++) {
      result += punctuationMap[punc[i]] || punc[i];
    }
    return result;
  }

  // --- 取代舊的 updateAllRomanizerOutput 函式 ---
function updateAllRomanizerOutput() {
  if (!romanizerOutput || !segmentationWorkspace) return;

  const allSpans = segmentationWorkspace.querySelectorAll('span');
  let resultString = '';

  allSpans.forEach(span => {
    let text;

    if (span.classList.contains('no-result')) {
      text = '<span class="placeholder-block"></span>';
    } else if (span.dataset.romanized) {
      // --- ↓↓↓ 【核心修改】根據連詞模式處理多音節詞彙 ↓↓↓ ---
      const syllables = span.dataset.romanized.split(' ');
      if (syllables.length > 1) {
        switch (romanizerJoiningMode) {
          case 'none':
            text = syllables.join('');
            break;
          case 'hyphen':
            text = syllables.join('-');
            break;
          case 'space':
          default:
            text = span.dataset.romanized; // 維持原樣
            break;
        }
      } else {
        // 單音節詞，毋使處理
        text = span.dataset.romanized;
      }
      // --- ↑↑↑ 【核心修改結束】 ↑↑↑ ---
    } else {
      // 處理標點符號
      text = normalizePunctuation(span.textContent);
    }
    resultString += text + ' ';
  });

  let finalHTML = resultString.trim();
  // 處理標點符號摎空白个處理邏輯 (維持不變)
  finalHTML = finalHTML.replace(/\s+([,.?!:;”’)])/g, '$1');
  finalHTML = finalHTML.replace(/([“‘(])\s+/g, '$1');
  finalHTML = finalHTML.replace(/([,.?!:;”’)])(?!["'’)])\s*/g, '$1 ');
  finalHTML = finalHTML.trim();

  romanizerOutput.innerHTML = finalHTML;
}
});