// HakSpring Romanizer (Romaine) - 「蘿蔓生菜」客語羅馬字轉換器
// Written by Roo, the AI Software Engineer
// Based on spec 1.4 generated by Gemini 2.5 Pro based on ideas of Aiuanyu

document.addEventListener('DOMContentLoaded', () => {
  let romanizerSelectedDialect = '四縣'; // <-- 新增此行，預設為「四縣」
  const ROMANIZER_JOINING_MODE_KEY = 'romanizerJoiningMode';
  let romanizerJoiningMode = 'none'; // 【新增】預設連詞模式

  // DOM Elements
  const showRomanizerBtn = document.getElementById('showRomanizerBtn');
  const romanizerContainer = document.getElementById('romanizerContainer');
  const romanizerCloseBtn = document.getElementById('romanizerCloseBtn');
  const romanizerStartBtn = document.getElementById('romanizer-start-btn');
  const segmentationWorkspace = document.getElementById('segmentation-workspace');
  const copyRomanizerResultBtn = document.getElementById('copy-romanizer-result-btn');
  const romanizerDialectSelector = document.getElementById('romanizer-dialect-selector');
  const romanizerJoiningModeSelector = document.getElementById('romanizer-joining-mode-selector'); // 【新增】
  const romanizerInput = document.getElementById('romanizer-input');
  const romanizerOutput = document.getElementById('romanizer-output');

  // 【新增】頁面載入時，讀取使用者偏好
  const savedJoiningMode = localStorage.getItem(ROMANIZER_JOINING_MODE_KEY);
  if (savedJoiningMode && romanizerJoiningModeSelector) {
    romanizerJoiningMode = savedJoiningMode;
    romanizerJoiningModeSelector.value = savedJoiningMode;
    console.log(`從 localStorage 載入連詞模式: ${savedJoiningMode}`);
  }

  // --- Event Listeners (修正後) ---
  if (romanizerDialectSelector) {
    romanizerDialectSelector.addEventListener('change', function() {
      romanizerSelectedDialect = this.value;
      console.log(`Romanizer 腔調已切換為: ${romanizerSelectedDialect}`);

      // --- ↓↓↓ 新增以下程式碼 ↓↓↓ ---
      if (segmentationWorkspace) {
        segmentationWorkspace.innerHTML = '';
      }
      if (romanizerOutput) {
        romanizerOutput.innerHTML = '';
      }
      // --- ↑↑↑ 新增結束 ↑↑↑ ---
    });
  }

  // 【新增】監聽連詞模式選擇器个變化
  if (romanizerJoiningModeSelector) {
    romanizerJoiningModeSelector.addEventListener('change', function() {
      romanizerJoiningMode = this.value;
      localStorage.setItem(ROMANIZER_JOINING_MODE_KEY, romanizerJoiningMode);
      console.log(`連詞模式已切換並儲存: ${romanizerJoiningMode}`);

      // 若工作區有內容，就即時更新結果
      if (segmentationWorkspace && segmentationWorkspace.innerHTML.trim() !== '') {
        updateAllRomanizerOutput();
      }
    });
  }
  if (showRomanizerBtn) {
    showRomanizerBtn.addEventListener('click', showRomanizer);
  }
  if (romanizerCloseBtn) {
    romanizerCloseBtn.addEventListener('click', hideRomanizer);
  }
  if (romanizerStartBtn) {
    romanizerStartBtn.addEventListener('click', startSegmentation);
  }
  if (segmentationWorkspace) {
    segmentationWorkspace.addEventListener('click', handleSegmentClick);
  }
  if (copyRomanizerResultBtn) {
    copyRomanizerResultBtn.addEventListener('click', copyRomanizerResult);
  }

  // --- 新增：監聽 output 區个點擊，處理大寫轉換 ---
  if (romanizerOutput) {
    romanizerOutput.addEventListener('click', function(event) {
      // 檢查點擊个係無係大寫按鈕
      if (event.target.classList.contains('uppercase-btn')) {
        const button = event.target;
        const wrapper = button.parentNode;

        // 尋著 wrapper 內背个文字節點
        for (const node of wrapper.childNodes) {
          if (node.nodeType === Node.TEXT_NODE && node.textContent.trim() !== '') {
            const currentText = node.textContent;

            // 【新邏輯】檢查第一個字母係無係大寫
            if (currentText[0] === currentText[0].toUpperCase()) {
              // 若係，就轉做全部小寫
              node.textContent = currentText.toLowerCase();
            } else {
              // 若無，就淨係將第一個字母轉做大寫
              node.textContent = currentText.charAt(0).toUpperCase() + currentText.slice(1);
            }
            break; // 處理完就跳出迴圈
          }
        }
      }
    });
  }

  // --- Functions (修正後) ---
  function showRomanizer() {
    if (romanizerContainer) {
      romanizerContainer.style.display = 'block';
      romanizerContainer.scrollIntoView({ behavior: 'smooth', block: 'start' });

      // --- 優化腔調擇單預設邏輯 ---
      if (typeof currentActiveMainDialectName !== 'undefined' && romanizerDialectSelector) {
        const mainDialect = currentActiveMainDialectName;
        // 檢查 main.js 傳來个腔調，係無係一個有效个選項
        const isValidOption = Array.from(romanizerDialectSelector.options).some(opt => opt.value === mainDialect);

        // 若係有效選項就用佢，若無 (例如係空字串)，就 fallback 到 '四縣'
        const dialectToSet = (mainDialect && isValidOption) ? mainDialect : '四縣';

        romanizerDialectSelector.value = dialectToSet;

        // 同步更新 Romanizer 內部个狀態變數
        romanizerSelectedDialect = romanizerDialectSelector.value;
        console.log(`Romanizer opened. Dialect set to: ${romanizerSelectedDialect}`);
      }
    }
  }

  function hideRomanizer() {
    if (romanizerContainer) {
      romanizerContainer.style.display = 'none';
    }
  }
  // --- 取代舊的 startSegmentation 函式 ---
function startSegmentation() {
  if (!romanizerInput || !segmentationWorkspace || !romanizerOutput) return;

  segmentationWorkspace.innerHTML = '';
  romanizerOutput.innerHTML = '';

  const text = romanizerInput.value;
  if (!text) return;

  // 【新】按換行符切分做多行
  const lines = text.split('\n');

  lines.forEach((line, lineIndex) => {
    // 【新】處理不大寫个例外指示符
    let suppressCapitalization = false;
    if (line.startsWith("'")) {
      suppressCapitalization = true;
      line = line.substring(1); // 拿忒指示符
    }

    const segmentRegex = /([^\u4e00-\u9fa5\u3400-\u4dbf\u{20000}-\u{2a6df}\u{2a700}-\u{2b73f}\u{2b740}-\u{2b81f}\u{2b820}-\u{2ceaf}\u{2ceb0}-\u{2ebef}]+)/u;
    const segments = line.split(segmentRegex).filter(Boolean);

    segments.forEach((segment, segmentIndex) => {
      const span = document.createElement('span');
      span.textContent = segment;

      // 【新】若係行首个例外情況，加上 data-* 屬性
      if (segmentIndex === 0 && suppressCapitalization) {
        span.dataset.noCapitalize = 'true';
      }

      if (!segmentRegex.test(segment)) {
        span.classList.add('segment-word');
        const readings = findPronunciationsInAllData(segment);
        const exactMatches = readings.filter(r => r.isExactMatch);

        if (exactMatches.length > 0) {
          const dialectSpecificMatches = exactMatches.filter(r => isSourceMatchingDialect(r.source, romanizerSelectedDialect));
          if (dialectSpecificMatches.length > 0) {
            const preferredReading = dialectSpecificMatches[0];
            span.dataset.romanized = preferredReading.pronunciation;
            span.classList.add('completed');
            const uniquePronunciationsInDialect = [...new Set(dialectSpecificMatches.map(r => r.pronunciation))];
            if (uniquePronunciationsInDialect.length > 1) {
              span.classList.add('auto-filled-multiple');
            }
          } else {
            span.dataset.romanized = '';
            span.classList.add('no-result');
          }
        } else {
          span.dataset.romanized = ''; // 無結果統一處理
          span.classList.add('no-result');
        }
      }
      segmentationWorkspace.appendChild(span);
    });

    // 【新】在每一行後壁（除了最尾一行）加上換行符
    if (lineIndex < lines.length - 1) {
      segmentationWorkspace.appendChild(document.createElement('br'));
    }
  });

  updateAllRomanizerOutput();
}
  function handleSegmentClick(event) {
    const target = event.target;
    // Make sure the clicked element is a word segment
    if (target.classList.contains('segment-word')) {
      const searchText = target.textContent;
      
      // Check if dependent functions from main.js exist
      if (typeof findPronunciationsInAllData !== 'function' || typeof showPronunciationPopup !== 'function') {
        console.error('Core functions (findPronunciationsInAllData or showPronunciationPopup) are not defined. Make sure main.js is loaded before romanizer.js.');
        alert('核心查詢功能載入失敗，請重新整理頁面。');
        return;
      }
      
      const readings = findPronunciationsInAllData(searchText);
      
      // Call the popup function, passing the clicked span as the anchor,
      // and a new callback function to handle the selection.
      // Call the new, self-contained popup function
      showPronunciationPopup(searchText, readings, target, (anchor, phonetic) => {
        updateRomanizerOutput(anchor, phonetic);
      }, romanizerSelectedDialect); // <-- 在此傳入 Romanizer 選擇的腔調
    }
  }
  function copyRomanizerResult() {
    if (!romanizerOutput || !copyRomanizerResultBtn) return;

    // 【新】用正規表示式將多隻空白換做一隻，再過 trim()
    const textToCopy = romanizerOutput.textContent.replace(/\s+/g, ' ').trim();

    if (textToCopy) {
      navigator.clipboard.writeText(textToCopy).then(() => {
        // Optional: Provide user feedback
        const originalButtonContent = copyRomanizerResultBtn.innerHTML;
        copyRomanizerResultBtn.innerHTML = '<i class="fas fa-check"></i> 已複製';
        copyRomanizerResultBtn.disabled = true;
        setTimeout(() => {
          copyRomanizerResultBtn.innerHTML = originalButtonContent;
          copyRomanizerResultBtn.disabled = false;
        }, 2000);
      }).catch(err => {
        console.error('無法複製文字: ', err);
        alert('複製失敗，請手動複製。');
      });
    }
  }
  function updateRomanizerOutput(targetSpan, selectedRomanization) {
    if (!targetSpan) return;
    targetSpan.dataset.romanized = selectedRomanization;
    targetSpan.classList.add('completed');
    targetSpan.classList.remove('auto-filled-multiple');
    targetSpan.classList.remove('no-result');
    updateAllRomanizerOutput();
  }

  // --- 新增：標點正規化函式 ---
  function normalizePunctuation(punc) {
    const punctuationMap = {
      '，': ',', '。': '.', '？': '?', '！': '!', '；': ';', '：': ':',
      '（': '(', '）': ')', '、': ',', // 頓號也轉做逗號
      '「': '“', '」': '”', '『': '‘', '』': '’'
    };
    // 逐一替換，處理連續標點个情況
    let result = '';
    for (let i = 0; i < punc.length; i++) {
      result += punctuationMap[punc[i]] || punc[i];
    }
    return result;
  }

/**
 * 根據客語連寫規則，在需要个地方插入分隔撇號 (')，避免音節混淆。
 * @param {string} spaceSeparatedSyllables - 用空白隔開个原始音節字串。
 * @returns {string} 處理後个連寫字串。
 */
function applyApostropheRules(spaceSeparatedSyllables) {
  if (!spaceSeparatedSyllables) return '';
  let text = spaceSeparatedSyllables;

  // 定義所有正規表示式規則
  const rules = [
    // 規則 1: C'V (特定輔音後接元音)
    { find: /([bdgmn]) ([aáǎàāâeéěèēêiíǐìīîoóǒòōôuúǔùūû])/g, replace: "$1'$2" },
    // 規則 2: a'iu
    { find: /([aáǎàāâ]) ([iíǐìīîuúǔùūû])/g, replace: "$1'$2" },
    // 規則 3: e'u
    { find: /([eéěèēê]) ([uúǔùūû])/g, replace: "$1'$2" },
    // 規則 4: i'V
    { find: /([iíǐìīî]) ([aáǎàāâeéěèēêiíǐìīîoóǒòōôuúǔùūû])/g, replace: "$1'$2" },
    // 規則 5: o'i
    { find: /([oóǒòōô]) ([iíǐìīî])/g, replace: "$1'$2" },
    // 規則 6: u'aei
    { find: /([uúǔùūû]) ([aáǎàāâeéěèēêiíǐìīî])/g, replace: "$1'$2" },
    // 規則 7: V'ng
    { find: /([aáǎàāâeéěèēêiíǐìīîoóǒòōôuúǔùūû]) ([nńňǹ]g)/g, replace: "$1'$2" },
    // 規則 8: n'g
    { find: /(n) (g)/g, replace: "$1'$2" }
  ];

  // 逐一應用規則，將符合條件个空白換做撇號
  rules.forEach(rule => {
    text = text.replace(rule.find, rule.replace);
  });

  // 最後，拿忒所有剩下个空白
  text = text.replace(/\s/g, '');

  return text;
}

  // --- 取代舊的 updateAllRomanizerOutput 函式 ---
function updateAllRomanizerOutput() {
  if (!romanizerOutput || !segmentationWorkspace) return;

  // 1. 清空舊个結果
  romanizerOutput.innerHTML = '';

  // 【新】直接處理所有子節點，包含 <span> 同 <br>
  const childNodes = Array.from(segmentationWorkspace.childNodes);

  childNodes.forEach(node => {
    // 若係 <br> 標籤，直接複製到 output
    if (node.nodeName === 'BR') {
      romanizerOutput.appendChild(document.createElement('br'));
      return; // 處理完畢，換下一個節點
    }

    // 若係一般个 <span> 節點
    if (node.nodeType === Node.ELEMENT_NODE && node.tagName === 'SPAN') {
      const span = node;
      if (span.classList.contains('no-result')) {
        const placeholder = document.createElement('span');
        placeholder.className = 'placeholder-block';
        romanizerOutput.appendChild(placeholder);
      } else if (span.dataset.romanized) {
        const syllables = span.dataset.romanized.split(' ').filter(s => s);
        syllables.forEach((syllable, index) => {
          const wrapper = document.createElement('span');
          wrapper.className = 'syllable-wrapper';
          // 【新】傳遞 no-capitalize 屬性
          if (span.dataset.noCapitalize) {
            wrapper.dataset.noCapitalize = 'true';
          }
          const textNode = document.createTextNode(syllable);
          const uppercaseBtn = document.createElement('button');
          uppercaseBtn.className = 'uppercase-btn';
          uppercaseBtn.textContent = 'U';
          uppercaseBtn.setAttribute('aria-label', `將 ${syllable} 轉做大寫`);
          wrapper.appendChild(textNode);
          wrapper.appendChild(uppercaseBtn);
          romanizerOutput.appendChild(wrapper);

          if (index < syllables.length - 1) {
            let separator = '';
            switch (romanizerJoiningMode) {
              case 'hyphen': separator = '-'; break;
              case 'space': separator = ' '; break;
              case 'none':
                const tempString = applyApostropheRules(`${syllable} ${syllables[index + 1]}`);
                if (tempString.includes("'")) separator = "'";
                break;
            }
            if (separator) romanizerOutput.appendChild(document.createTextNode(separator));
          }
        });
      } else {
        const puncText = normalizePunctuation(span.textContent);
        const puncNode = document.createTextNode(puncText);
        romanizerOutput.appendChild(puncNode);
      }
    }
  });

  // 2. 後處理：整理標點符號前後个空白
  let finalHTML = romanizerOutput.innerHTML;
  finalHTML = finalHTML.replace(/\s+([,.?!:;”’)])/g, '$1');
  finalHTML = finalHTML.replace(/([“‘(])\s+/g, '$1');
  finalHTML = finalHTML.replace(/([,.?!:;”’)])(?!["'’)])\s*/g, '$1 ');
  romanizerOutput.innerHTML = finalHTML.trim();

  // --- ↓↓↓ 【重構】自動句首大寫邏輯 ↓↓↓ ---
  let capitalizeNext = true; // 預設第一隻音節愛大寫
  const outputNodes = Array.from(romanizerOutput.childNodes);

  for (const node of outputNodes) {
    // 規則 a & c: 若係愛大寫，而且目前節點係音節 wrapper
    if (capitalizeNext && node.nodeType === Node.ELEMENT_NODE && node.classList.contains('syllable-wrapper')) {
      // 檢查係無係有「毋使大寫」个指示
      if (!node.dataset.noCapitalize) {
        const textNode = Array.from(node.childNodes).find(n => n.nodeType === Node.TEXT_NODE);
        if (textNode) {
          const text = textNode.textContent;
          textNode.textContent = text.charAt(0).toUpperCase() + text.slice(1);
        }
      }
      capitalizeNext = false; // 無論有做無，處理完第一隻音節後就重設旗標
    }
    // 規則 b: 若目前節點係文字，檢查係無係以「句點」結束
    else if (node.nodeType === Node.TEXT_NODE) {
      const text = node.textContent.trim();
      if (text.endsWith('.')) { // 【新】淨檢查句點
        capitalizeNext = true; // 係，表示下一隻音節愛大寫
      }
    }
    // 規則 a: 若目前節點係換行 <br>，表示下一隻音節係行首，愛大寫
    else if (node.nodeName === 'BR') {
      capitalizeNext = true;
    }
  }
  // --- ↑↑↑ 自動句首大寫邏輯結束 ↑↑↑ ---
}
});